<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\BmnPengajuanrkbmnbagian;

class BmnPengajuanrkbmnbagianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Truncate the table before seeding
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        BmnPengajuanrkbmnbagian::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = [
            [
                'id' => 1,
                'kode_jenis_pengajuan' => 'R1-001',
                'id_bagian_pengusul' => 1,
                'id_biro_pengusul' => 101,
                'id_bagian_pelaksana' => 20,
                'id_biro_pelaksana' => 201,
                'program' => 'Program Peningkatan Sarana',
                'kegiatan' => 'Pembangunan Gedung Kantor',
                'output' => 'Gedung Kantor Baru',
                'kode_barang' => '2.11.03.01.005',
                'status' => 'approved',
                'tahun_anggaran' => 2024,
                'tanggal_pengajuan' => '2024-02-20',
                'tujuan_rencana' => 'Pembangunan gedung baru 2 lantai',
                'atr_nonatr' => 'NON-ATR',
                'skema' => 'Pembangunan',
                'harga_barang' => 3000000000,
                'total_anggaran' => 3000000000,
                'uraian_barang' => 'Pembangunan gedung kantor baru 2 lantai seluas 1000m2',
                'kuantitas' => 1,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 2,
                'kode_jenis_pengajuan' => 'R1-002',
                'id_bagian_pengusul' => 1,
                'id_biro_pengusul' => 101,
                'id_bagian_pelaksana' => 21,
                'id_biro_pelaksana' => 202,
                'program' => 'Program Peningkatan Sarana',
                'kegiatan' => 'Renovasi Bangunan Kantor',
                'output' => 'Gedung yang terawat',
                'kode_barang' => '2.11.01.01.001',
                'status' => 'completed',
                'tahun_anggaran' => 2023,
                'tanggal_pengajuan' => '2023-10-15',
                'tujuan_rencana' => 'Renovasi lobby utama',
                'atr_nonatr' => 'NON-ATR',
                'skema' => 'Renovasi',
                'harga_barang' => 250000000,
                'total_anggaran' => 250000000,
                'uraian_barang' => 'Renovasi interior lobby utama gedung',
                'kuantitas' => 1,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 3,
                'kode_jenis_pengajuan' => 'R3-001',
                'id_bagian_pengusul' => 2,
                'id_biro_pengusul' => 102,
                'id_bagian_pelaksana' => 22,
                'id_biro_pelaksana' => 203,
                'program' => 'Program Peningkatan Kesejahteraan',
                'kegiatan' => 'Pembangunan Rumah Negara',
                'output' => 'Tersedianya Rumah Negara Tipe C',
                'kode_barang' => '2.12.01.01.003',
                'status' => 'pending',
                'tahun_anggaran' => 2024,
                'tanggal_pengajuan' => '2024-05-12',
                'tujuan_rencana' => 'Pembangunan 5 unit rumah negara untuk pegawai',
                'atr_nonatr' => 'NON-ATR',
                'skema' => 'Pembangunan',
                'harga_barang' => 300000000,
                'total_anggaran' => 1500000000,
                'uraian_barang' => 'Pembangunan 5 unit rumah negara Tipe C',
                'kuantitas' => 5,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 4,
                'kode_jenis_pengajuan' => 'R3-002',
                'id_bagian_pengusul' => 2,
                'id_biro_pengusul' => 102,
                'id_bagian_pelaksana' => 22,
                'id_biro_pelaksana' => 203,
                'program' => 'Program Peningkatan Kesejahteraan',
                'kegiatan' => 'Pembangunan Rumah Negara',
                'output' => 'Tersedianya Rumah Negara Tipe D',
                'kode_barang' => '2.12.01.01.004',
                'status' => 'rejected',
                'tahun_anggaran' => 2025,
                'tanggal_pengajuan' => '2024-06-10',
                'tujuan_rencana' => 'Pembangunan 10 unit rumah negara untuk pegawai',
                'atr_nonatr' => 'NON-ATR',
                'skema' => 'Pembangunan',
                'harga_barang' => 200000000,
                'total_anggaran' => 2000000000,
                'uraian_barang' => 'Pembangunan 10 unit rumah negara Tipe D',
                'kuantitas' => 10,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 5,
                'kode_jenis_pengajuan' => 'R4-001',
                'id_bagian_pengusul' => 1,
                'id_biro_pengusul' => 101,
                'id_bagian_pelaksana' => 20,
                'id_biro_pelaksana' => 201,
                'program' => 'Program Dukungan Manajemen',
                'kegiatan' => 'Pengadaan Kendaraan Jabatan',
                'output' => 'Tersedianya Kendaraan',
                'kode_barang' => '3.02.01.01.001',
                'status' => 'approved',
                'tahun_anggaran' => 2024,
                'tanggal_pengajuan' => '2024-01-15',
                'tujuan_rencana' => 'Kendaraan Eselon II',
                'atr_nonatr' => 'ATR',
                'skema' => 'Reguler',
                'harga_barang' => 450000000,
                'total_anggaran' => 450000000,
                'uraian_barang' => 'Pengadaan 1 unit Mobil SUV',
                'kuantitas' => 1,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 6,
                'kode_jenis_pengajuan' => 'R4-002',
                'id_bagian_pengusul' => 3,
                'id_biro_pengusul' => 103,
                'id_bagian_pelaksana' => 20,
                'id_biro_pelaksana' => 201,
                'program' => 'Program Dukungan Manajemen',
                'kegiatan' => 'Pengadaan Kendaraan Jabatan',
                'output' => 'Tersedianya Kendaraan',
                'kode_barang' => '3.02.01.01.002',
                'status' => 'in_progress',
                'tahun_anggaran' => 2024,
                'tanggal_pengajuan' => '2024-06-01',
                'tujuan_rencana' => 'Kendaraan Eselon I',
                'atr_nonatr' => 'ATR',
                'skema' => 'Reguler',
                'harga_barang' => 700000000,
                'total_anggaran' => 700000000,
                'uraian_barang' => 'Pengadaan 1 unit Mobil Sedan 2500cc',
                'kuantitas' => 1,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 7,
                'kode_jenis_pengajuan' => 'R5-001',
                'id_bagian_pengusul' => 1,
                'id_biro_pengusul' => 101,
                'id_bagian_pelaksana' => 21,
                'id_biro_pelaksana' => 202,
                'program' => 'Program Dukungan Manajemen',
                'kegiatan' => 'Pengadaan Kendaraan Operasional',
                'output' => 'Tersedianya Kendaraan Operasional',
                'kode_barang' => '3.02.01.01.003',
                'status' => 'draft',
                'tahun_anggaran' => 2025,
                'tanggal_pengajuan' => '2024-03-10',
                'tujuan_rencana' => 'Kendaraan untuk operasional lapangan',
                'atr_nonatr' => 'ATR',
                'skema' => 'Reguler',
                'harga_barang' => 250000000,
                'total_anggaran' => 500000000,
                'uraian_barang' => 'Pengadaan 2 unit mobil operasional MPV',
                'kuantitas' => 2,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 8,
                'kode_jenis_pengajuan' => 'R5-002',
                'id_bagian_pengusul' => 4,
                'id_biro_pengusul' => 104,
                'id_bagian_pelaksana' => 20,
                'id_biro_pelaksana' => 201,
                'program' => 'Program Dukungan Manajemen',
                'kegiatan' => 'Pengadaan Kendaraan Roda 2',
                'output' => 'Tersedianya Kendaraan Operasional',
                'kode_barang' => '3.02.01.01.004',
                'status' => 'approved',
                'tahun_anggaran' => 2023,
                'tanggal_pengajuan' => '2023-11-20',
                'tujuan_rencana' => 'Motor untuk kurir surat',
                'atr_nonatr' => 'ATR',
                'skema' => 'Reguler',
                'harga_barang' => 30000000,
                'total_anggaran' => 90000000,
                'uraian_barang' => 'Pengadaan 3 unit motor matic 150cc',
                'kuantitas' => 3,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 9,
                'kode_jenis_pengajuan' => 'R6-001',
                'id_bagian_pengusul' => 3,
                'id_biro_pengusul' => 103,
                'id_bagian_pelaksana' => 20,
                'id_biro_pelaksana' => 201,
                'program' => 'Program Dukungan Teknis',
                'kegiatan' => 'Pengadaan Kendaraan Fungsional',
                'output' => 'Tersedianya Bus Jemputan',
                'kode_barang' => '3.02.01.02.001',
                'status' => 'approved',
                'tahun_anggaran' => 2024,
                'tanggal_pengajuan' => '2024-04-05',
                'tujuan_rencana' => 'Bus untuk antar jemput pegawai',
                'atr_nonatr' => 'ATR',
                'skema' => 'Reguler',
                'harga_barang' => 800000000,
                'total_anggaran' => 1600000000,
                'uraian_barang' => 'Pengadaan 2 unit Bus ukuran sedang',
                'kuantitas' => 2,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
            [
                'id' => 10,
                'kode_jenis_pengajuan' => 'R6-002',
                'id_bagian_pengusul' => 5,
                'id_biro_pengusul' => 105,
                'id_bagian_pelaksana' => 20,
                'id_biro_pelaksana' => 201,
                'program' => 'Program Dukungan Manajemen',
                'kegiatan' => 'Pengadaan Kendaraan Fungsional',
                'output' => 'Tersedianya Truk Sampah',
                'kode_barang' => '3.02.01.02.002',
                'status' => 'draft',
                'tahun_anggaran' => 2025,
                'tanggal_pengajuan' => '2024-06-05',
                'tujuan_rencana' => 'Truk untuk angkut sampah',
                'atr_nonatr' => 'ATR',
                'skema' => 'Reguler',
                'harga_barang' => 550000000,
                'total_anggaran' => 550000000,
                'uraian_barang' => 'Pengadaan 1 unit truk sampah',
                'kuantitas' => 1,
                'created_at' => '2025-10-28 03:05:21',
                'updated_at' => '2025-10-28 03:05:21'
            ],
        ];

        DB::table('bmn_pengajuanrkbmnbagian')->insert($data);
    }
}